kind: Cluster
networking:
  apiServerAddress: 0.0.0.0
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- extraPortMappings:
  - hostPort: 80
    containerPort: 80
    protocol: TCP
  - hostPort: 443
    containerPort: 443
    protocol: TCP
    # Everything below here is a portmapping from 30,000 --> 31,000 to make it easy to bind debugging ports to the control plane.
    # if you need to debug an API, make sure that it either fits within this range, or modify this list and rebuild your kind cluster: kind delete cluster; ./src/controlplane/local/automation/new-cluster.ps1
  - containerPort: 30000
    hostPort: 30000
    protocol: TCP
  - containerPort: 30001
    hostPort: 30001
    protocol: TCP
  - containerPort: 30002
    hostPort: 30002
    protocol: TCP
  - containerPort: 30003
    hostPort: 30003
    protocol: TCP
  - containerPort: 30004
    hostPort: 30004
    protocol: TCP
  - containerPort: 30005
    hostPort: 30005
    protocol: TCP
  - containerPort: 30006
    hostPort: 30006
    protocol: TCP
  - containerPort: 30007
    hostPort: 30007
    protocol: TCP
  - containerPort: 30008
    hostPort: 30008
    protocol: TCP
  - containerPort: 30009
    hostPort: 30009
    protocol: TCP
  - containerPort: 30010
    hostPort: 30010
    protocol: TCP
  - containerPort: 30011
    hostPort: 30011
    protocol: TCP
  - containerPort: 30012
    hostPort: 30012
    protocol: TCP
  - containerPort: 30013
    hostPort: 30013
    protocol: TCP
  - containerPort: 30014
    hostPort: 30014
    protocol: TCP
  - containerPort: 30015
    hostPort: 30015
    protocol: TCP
  - containerPort: 30016
    hostPort: 30016
    protocol: TCP
  - containerPort: 30017
    hostPort: 30017
    protocol: TCP
  - containerPort: 30018
    hostPort: 30018
    protocol: TCP
  - containerPort: 30019
    hostPort: 30019
    protocol: TCP
  - containerPort: 30020
    hostPort: 30020
    protocol: TCP
  - containerPort: 30021
    hostPort: 30021
    protocol: TCP
  - containerPort: 30022
    hostPort: 30022
    protocol: TCP
  - containerPort: 30023
    hostPort: 30023
    protocol: TCP
  - containerPort: 30024
    hostPort: 30024
    protocol: TCP
  - containerPort: 30025
    hostPort: 30025
    protocol: TCP
  - containerPort: 30026
    hostPort: 30026
    protocol: TCP
  - containerPort: 30027
    hostPort: 30027
    protocol: TCP
  - containerPort: 30028
    hostPort: 30028
    protocol: TCP
  - containerPort: 30029
    hostPort: 30029
    protocol: TCP
  - containerPort: 30030
    hostPort: 30030
    protocol: TCP
  - containerPort: 30031
    hostPort: 30031
    protocol: TCP
  - containerPort: 30032
    hostPort: 30032
    protocol: TCP
  - containerPort: 30033
    hostPort: 30033
    protocol: TCP
  - containerPort: 30034
    hostPort: 30034
    protocol: TCP
  - containerPort: 30035
    hostPort: 30035
    protocol: TCP
  - containerPort: 30036
    hostPort: 30036
    protocol: TCP
  - containerPort: 30037
    hostPort: 30037
    protocol: TCP
  - containerPort: 30038
    hostPort: 30038
    protocol: TCP
  - containerPort: 30039
    hostPort: 30039
    protocol: TCP
  - containerPort: 30040
    hostPort: 30040
    protocol: TCP
  - containerPort: 30041
    hostPort: 30041
    protocol: TCP
  - containerPort: 30042
    hostPort: 30042
    protocol: TCP
  - containerPort: 30043
    hostPort: 30043
    protocol: TCP
  - containerPort: 30044
    hostPort: 30044
    protocol: TCP
  - containerPort: 30045
    hostPort: 30045
    protocol: TCP
  - containerPort: 30046
    hostPort: 30046
    protocol: TCP
  - containerPort: 30047
    hostPort: 30047
    protocol: TCP
  - containerPort: 30048
    hostPort: 30048
    protocol: TCP
  - containerPort: 30049
    hostPort: 30049
    protocol: TCP
  - containerPort: 30050
    hostPort: 30050
    protocol: TCP
  - containerPort: 30051
    hostPort: 30051
    protocol: TCP
  - containerPort: 30052
    hostPort: 30052
    protocol: TCP
  - containerPort: 30053
    hostPort: 30053
    protocol: TCP
  - containerPort: 30054
    hostPort: 30054
    protocol: TCP
  - containerPort: 30055
    hostPort: 30055
    protocol: TCP
  - containerPort: 30056
    hostPort: 30056
    protocol: TCP
  - containerPort: 30057
    hostPort: 30057
    protocol: TCP
  - containerPort: 30058
    hostPort: 30058
    protocol: TCP
  - containerPort: 30059
    hostPort: 30059
    protocol: TCP
  - containerPort: 30060
    hostPort: 30060
    protocol: TCP
  - containerPort: 30061
    hostPort: 30061
    protocol: TCP
  - containerPort: 30062
    hostPort: 30062
    protocol: TCP
  - containerPort: 30063
    hostPort: 30063
    protocol: TCP
  - containerPort: 30064
    hostPort: 30064
    protocol: TCP
  - containerPort: 30065
    hostPort: 30065
    protocol: TCP
  - containerPort: 30066
    hostPort: 30066
    protocol: TCP
  - containerPort: 30067
    hostPort: 30067
    protocol: TCP
  - containerPort: 30068
    hostPort: 30068
    protocol: TCP
  - containerPort: 30069
    hostPort: 30069
    protocol: TCP
  - containerPort: 30070
    hostPort: 30070
    protocol: TCP
  - containerPort: 30071
    hostPort: 30071
    protocol: TCP
  - containerPort: 30072
    hostPort: 30072
    protocol: TCP
  - containerPort: 30073
    hostPort: 30073
    protocol: TCP
  - containerPort: 30074
    hostPort: 30074
    protocol: TCP
  - containerPort: 30075
    hostPort: 30075
    protocol: TCP
  - containerPort: 30076
    hostPort: 30076
    protocol: TCP
  - containerPort: 30077
    hostPort: 30077
    protocol: TCP
  - containerPort: 30078
    hostPort: 30078
    protocol: TCP
  - containerPort: 30079
    hostPort: 30079
    protocol: TCP
  - containerPort: 30080
    hostPort: 30080
    protocol: TCP
  - containerPort: 30081
    hostPort: 30081
    protocol: TCP
  - containerPort: 30082
    hostPort: 30082
    protocol: TCP
  - containerPort: 30083
    hostPort: 30083
    protocol: TCP
  - containerPort: 30084
    hostPort: 30084
    protocol: TCP
  - containerPort: 30085
    hostPort: 30085
    protocol: TCP
  - containerPort: 30086
    hostPort: 30086
    protocol: TCP
  - containerPort: 30087
    hostPort: 30087
    protocol: TCP
  - containerPort: 30088
    hostPort: 30088
    protocol: TCP
  - containerPort: 30089
    hostPort: 30089
    protocol: TCP
  - containerPort: 30090
    hostPort: 30090
    protocol: TCP
  - containerPort: 30091
    hostPort: 30091
    protocol: TCP
  - containerPort: 30092
    hostPort: 30092
    protocol: TCP
  - containerPort: 30093
    hostPort: 30093
    protocol: TCP
  - containerPort: 30094
    hostPort: 30094
    protocol: TCP
  - containerPort: 30095
    hostPort: 30095
    protocol: TCP
  - containerPort: 30096
    hostPort: 30096
    protocol: TCP
  - containerPort: 30097
    hostPort: 30097
    protocol: TCP
  - containerPort: 30098
    hostPort: 30098
    protocol: TCP
  - containerPort: 30099
    hostPort: 30099
    protocol: TCP
  - containerPort: 30100
    hostPort: 30100
    protocol: TCP
  - containerPort: 30101
    hostPort: 30101
    protocol: TCP
  - containerPort: 30102
    hostPort: 30102
    protocol: TCP
  - containerPort: 30103
    hostPort: 30103
    protocol: TCP
  - containerPort: 30104
    hostPort: 30104
    protocol: TCP
  - containerPort: 30105
    hostPort: 30105
    protocol: TCP
  - containerPort: 30106
    hostPort: 30106
    protocol: TCP
  - containerPort: 30107
    hostPort: 30107
    protocol: TCP
  - containerPort: 30108
    hostPort: 30108
    protocol: TCP
  - containerPort: 30109
    hostPort: 30109
    protocol: TCP
  - containerPort: 30110
    hostPort: 30110
    protocol: TCP
  - containerPort: 30111
    hostPort: 30111
    protocol: TCP
  - containerPort: 30112
    hostPort: 30112
    protocol: TCP
  - containerPort: 30113
    hostPort: 30113
    protocol: TCP
  - containerPort: 30114
    hostPort: 30114
    protocol: TCP
  - containerPort: 30115
    hostPort: 30115
    protocol: TCP
  - containerPort: 30116
    hostPort: 30116
    protocol: TCP
  - containerPort: 30117
    hostPort: 30117
    protocol: TCP
  - containerPort: 30118
    hostPort: 30118
    protocol: TCP
  - containerPort: 30119
    hostPort: 30119
    protocol: TCP
  - containerPort: 30120
    hostPort: 30120
    protocol: TCP
  - containerPort: 30121
    hostPort: 30121
    protocol: TCP
  - containerPort: 30122
    hostPort: 30122
    protocol: TCP
  - containerPort: 30123
    hostPort: 30123
    protocol: TCP
  - containerPort: 30124
    hostPort: 30124
    protocol: TCP
  - containerPort: 30125
    hostPort: 30125
    protocol: TCP
  - containerPort: 30126
    hostPort: 30126
    protocol: TCP
  - containerPort: 30127
    hostPort: 30127
    protocol: TCP
  - containerPort: 30128
    hostPort: 30128
    protocol: TCP
  - containerPort: 30129
    hostPort: 30129
    protocol: TCP
  - containerPort: 30130
    hostPort: 30130
    protocol: TCP
  - containerPort: 30131
    hostPort: 30131
    protocol: TCP
  - containerPort: 30132
    hostPort: 30132
    protocol: TCP
  - containerPort: 30133
    hostPort: 30133
    protocol: TCP
  - containerPort: 30134
    hostPort: 30134
    protocol: TCP
  - containerPort: 30135
    hostPort: 30135
    protocol: TCP
  - containerPort: 30136
    hostPort: 30136
    protocol: TCP
  - containerPort: 30137
    hostPort: 30137
    protocol: TCP
  - containerPort: 30138
    hostPort: 30138
    protocol: TCP
  - containerPort: 30139
    hostPort: 30139
    protocol: TCP
  - containerPort: 30140
    hostPort: 30140
    protocol: TCP
  - containerPort: 30141
    hostPort: 30141
    protocol: TCP
  - containerPort: 30142
    hostPort: 30142
    protocol: TCP
  - containerPort: 30143
    hostPort: 30143
    protocol: TCP
  - containerPort: 30144
    hostPort: 30144
    protocol: TCP
  - containerPort: 30145
    hostPort: 30145
    protocol: TCP
  - containerPort: 30146
    hostPort: 30146
    protocol: TCP
  - containerPort: 30147
    hostPort: 30147
    protocol: TCP
  - containerPort: 30148
    hostPort: 30148
    protocol: TCP
  - containerPort: 30149
    hostPort: 30149
    protocol: TCP
  - containerPort: 30150
    hostPort: 30150
    protocol: TCP
  - containerPort: 30151
    hostPort: 30151
    protocol: TCP
  - containerPort: 30152
    hostPort: 30152
    protocol: TCP
  - containerPort: 30153
    hostPort: 30153
    protocol: TCP
  - containerPort: 30154
    hostPort: 30154
    protocol: TCP
  - containerPort: 30155
    hostPort: 30155
    protocol: TCP
  - containerPort: 30156
    hostPort: 30156
    protocol: TCP
  - containerPort: 30157
    hostPort: 30157
    protocol: TCP
  - containerPort: 30158
    hostPort: 30158
    protocol: TCP
  - containerPort: 30159
    hostPort: 30159
    protocol: TCP
  - containerPort: 30160
    hostPort: 30160
    protocol: TCP
  - containerPort: 30161
    hostPort: 30161
    protocol: TCP
  - containerPort: 30162
    hostPort: 30162
    protocol: TCP
  - containerPort: 30163
    hostPort: 30163
    protocol: TCP
  - containerPort: 30164
    hostPort: 30164
    protocol: TCP
  - containerPort: 30165
    hostPort: 30165
    protocol: TCP
  - containerPort: 30166
    hostPort: 30166
    protocol: TCP
  - containerPort: 30167
    hostPort: 30167
    protocol: TCP
  - containerPort: 30168
    hostPort: 30168
    protocol: TCP
  - containerPort: 30169
    hostPort: 30169
    protocol: TCP
  - containerPort: 30170
    hostPort: 30170
    protocol: TCP
  - containerPort: 30171
    hostPort: 30171
    protocol: TCP
  - containerPort: 30172
    hostPort: 30172
    protocol: TCP
  - containerPort: 30173
    hostPort: 30173
    protocol: TCP
  - containerPort: 30174
    hostPort: 30174
    protocol: TCP
  - containerPort: 30175
    hostPort: 30175
    protocol: TCP
  - containerPort: 30176
    hostPort: 30176
    protocol: TCP
  - containerPort: 30177
    hostPort: 30177
    protocol: TCP
  - containerPort: 30178
    hostPort: 30178
    protocol: TCP
  - containerPort: 30179
    hostPort: 30179
    protocol: TCP
  - containerPort: 30180
    hostPort: 30180
    protocol: TCP
  - containerPort: 30181
    hostPort: 30181
    protocol: TCP
  - containerPort: 30182
    hostPort: 30182
    protocol: TCP
  - containerPort: 30183
    hostPort: 30183
    protocol: TCP
  - containerPort: 30184
    hostPort: 30184
    protocol: TCP
  - containerPort: 30185
    hostPort: 30185
    protocol: TCP
  - containerPort: 30186
    hostPort: 30186
    protocol: TCP
  - containerPort: 30187
    hostPort: 30187
    protocol: TCP
  - containerPort: 30188
    hostPort: 30188
    protocol: TCP
  - containerPort: 30189
    hostPort: 30189
    protocol: TCP
  - containerPort: 30190
    hostPort: 30190
    protocol: TCP
  - containerPort: 30191
    hostPort: 30191
    protocol: TCP
  - containerPort: 30192
    hostPort: 30192
    protocol: TCP
  - containerPort: 30193
    hostPort: 30193
    protocol: TCP
  - containerPort: 30194
    hostPort: 30194
    protocol: TCP
  - containerPort: 30195
    hostPort: 30195
    protocol: TCP
  - containerPort: 30196
    hostPort: 30196
    protocol: TCP
  - containerPort: 30197
    hostPort: 30197
    protocol: TCP
  - containerPort: 30198
    hostPort: 30198
    protocol: TCP
  - containerPort: 30199
    hostPort: 30199
    protocol: TCP
  - containerPort: 30200
    hostPort: 30200
    protocol: TCP
  extraMounts:
  - hostPath: /keycloakdb
    containerPath: /postgres/wizards/keycloakdb
  role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"

