apiVersion: v1
kind: PersistentVolume
metadata:
  name: localdev-volume
  labels:
    type: local
spec:
  storageClassName: localdev
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mongodata"  # this assumes that there's a directory 'mongodata' on the kind control plane node. /mongodata is created as part of the controlplane init automation.
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: localdev-claim
spec:
  storageClassName: localdev # this comes from /k8s/local/dev-volume.yaml
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    name: mongo
spec:
  ports:
    - port: 27017
      targetPort: 27017
  clusterIP: None  # this makes this service a 'Headless Service'
  selector:
    app: mongo
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
spec:
  selector:
    matchLabels:
      app: mongo
  serviceName: mongo
  replicas: 1
  template:
    metadata:
      labels:
        app: mongo
    spec:
      volumes:
      - name: localdev-storage
        persistentVolumeClaim:
          claimName: localdev-claim
      terminationGracePeriodSeconds: 10
      containers:
      - name: mongo
        image: mongo
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-initdb-root-secret
              key: username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-initdb-root-secret
              key: password
        ports:
          - containerPort: 27017
        volumeMounts:
          - name: localdev-storage
            mountPath: /data/db